services:
  dabai:
    image: ghcr.io/screamlab/pros_jetson_driver_image:0.1.0
    container_name: camera_gemini
    env_file:
      - .env
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    networks:
      - my_bridge_network
    command:
    - ros2
    - launch
    - orbbec_camera
    - gemini_ew.launch.py
    - color_fps:=30
    - depth_fps:=30

  compress:
    image: ghcr.io/screamlab/pros_jetson_driver_image:0.1.0
    container_name: camera_gemini_compress
    env_file:
      - .env
    networks:
      - my_bridge_network
    depends_on:
      - dabai
    command: "ros2 run image_transport republish raw --ros-args --remap in:=camera/color/image_raw -p out:=camera/compressed"

networks:
  my_bridge_network:
    driver: bridge
